### ISSUE TITLE
consider httr at least for authentication

### ISSUE THREAD

**Issue by cboettig** [karthik/rDrop#15]
If it's not broken don't fix it is a perfectly good answer here.  But, should you go the httr route to get this on CRAN I think it will make the authentication much more streamlined; e.g. user should be able to either give a PAT or otherwise just issue any rDrop command and be asked to confirm in the browser without ever having to copy API keys anywhere etc.

**Comment by karthik** [comment]
:+1:  Yep, I'm on the case now. Between Hadley's request and also the Travis artefacts thing, I'll switch the whole thing over to httr soon.
