### ISSUE TITLE
dropbox_put seems to fail with larger files

### ISSUE THREAD

**Issue by Melsteroni** [karthik/rDrop#17]
This looks awesome...thanks for putting together this package. 

I seem to be having trouble getting large zip files to upload.  I get this message:

> file.info("plumes_fert_test.zip")$size
[1] 69747906
> dropbox_put(dropbox_credentials, what="plumes_fert_test.zip", filename='CHI/plumes_fert_test.zip')
Error in fromJSON(OAuthRequest(cred, url, , "PUT", upload = TRUE, readfunction = input,  : 
  error in evaluating the argument 'content' in selecting a method for function 'fromJSON': Error in function (type, msg, asError = TRUE)  : 
  Failed sending data to the peer

I tried with a similarly sized file and it continued to fail. Interestingly, a zipfile with the correct name was added to my dropbox account, but it was empty. 

Then I tried with a couple smaller .zip files and it seemed to work.  So it seems like it might be related to size.

Is there something obvious I am doing wrong....or is this a known issue?

Thanks!

**Comment by karthik** [comment]
Thanks for the note and the bug report. rDrop has some ongoing issues but I've begun a more robust replacement called rDrop2 where all these issues should go away. It's two weeks away from an installable beta and I'll drop you a note as soon as it's ready.

**Comment by karthik** [comment]
I have deprecated this package in favor of a new replacement: See https://github.com/karthik/rDrop2 and file any issues there. Thanks
